server:
  port: 8091

spring:
  application:
    name: USERS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8092/eureka
  instance:
    hostname: localhost